<script>

    (function() {
        var $divResources = $("div[name='resources']", elements.body);

        $("form", elements.dialog).on("submit", function(e) {
            e.preventDefault();

            Core.ajax({
                "url": "/admin/acl/resource/ajax/move/id:<?php echo $this->resource->id; ?>",
                "data": {
                    "parent_id": getSelectedResource()
                },
                "success": function(response) {
                    if (response.status === 'good') {
                        location.reload(true);
                    } else {
                        alert(response.message || "Resource could not be moved");
                    }
                }
            });
        });

        var menuAdd = function($holder, options, selected) {

            var $select   = $("<select>");
            var $children = $("<div>");

            if (! $.isEmptyObject(options)) {

                $("<option>").appendTo($select);

                for (var k in options) {
                    var $option = $("<option>")
                        .attr("value", k)
                        .text(options[k]);

                    $select.append($option);

                    if (k == selected) {
                        $option.prop("selected", true);
                    }
                }
            } else {
                $select
                    .prop("disabled", true)
                    .append(
                        $("<option>")
                    );
            }

            $select.on("change", menuChange);

            $holder
                .append($select)
                .append($children);

            return $children;
        };

        var menuChange = function(e) {
            var $this = $(this);
            var $children = $this.next("div");
            $children.empty();

            Core.ajax({
                "url": "/admin/acl/resource/ajax/children/id:" + $this.val(),
                "success": function(response) {
                    if (response.status === 'good') {
                        menuAdd(
                            $children,
                            response.children
                        );
                    } else {
                        CoreDialog.error("Error loading child resources");
                    }
                }
            });
        };

        var getSelectedResource = function() {
            var $select = $("select", $divResources);
            while (1) {
                var $next = $("select", $select.next("div"));
                if ($next.length && $next.val()) {
                    $select = $next;
                } else {
                    return $select.val();
                }
            }
        };

        <?php
            $ancestors = $this->resource->ancestors();
            $ancestor_ids = [];
            foreach ($ancestors as $ancestor) {
                $ancestor_ids[] = $ancestor->id;
            }
            $order_by = [ 'name' => neoform\entity\dao::SORT_ASC, ];
        ?>

        var $holder = menuAdd(
            $divResources,
            <?php echo json_encode($this->root_resources->field('name', 'id')); ?>,
            <?php echo isset($ancestor_ids[0]) ? $ancestor_ids[0] : 'null'; ?>
        );

        <?php foreach ($this->resource->ancestors() as $i => $resource): ?>
            $holder = menuAdd(
                $holder,
                <?php echo json_encode($resource->child_acl_resource_collection($order_by)->field('name', 'id')); ?>,
                <?php echo isset($ancestor_ids[$i+1]) ? $ancestor_ids[$i+1] : 'null'; ?>
            );
        <?php endforeach; ?>

    })();

</script>