<form name="login" style="margin: 0 auto; display: block;">	
    <div class="regular-body" style="padding: 0 0 10px 0;">
    	<div class="padded info" id="message">
        	Please login to continue        	
    	</div>
    	<table width="100%">
    		<tr>
    			<td width="90" align="right">			
    				<strong>Email</strong>
    			</td>
    			<td width="10">&nbsp;</td>
    			<td>
    				<input type="text" name="email" style="width: 403px; font-size: 14px; line-height: 18px; padding: 5px 8px;" tabindex="1" />
    			</td>
    		</tr>
    		<tr>
    			<td width="90" align="right">
    				<strong>Password</strong>
    			</td>
    			<td width="10">&nbsp;</td>
    			<td>
    				<input type="password" name="password" style="width: 220px; font-size: 14px; line-height: 18px; padding: 5px 8px;" tabindex="2" />
    				&nbsp;
    				<a href="/account/passwordretreive" class="button" name="lostpassword">Forgot Your Password?</a>
    			</td>
    		</tr>
    	</table>
    	<div style="margin: 5px 0 0 100px;">
			<input type="checkbox" name="remember" id="login_remember" tabindex="3" />
        	<label for="login_remember">Keep me logged in</label>
    	</div>
    </div>
    <input type="submit" style="position: fixed; left: -9999px"/>
</form>
