<?php $this->inc('admin/templates/header'); ?>

<script>
    (function(){
        var self = {},
            div;


        /**
         * Init
         */
        $(function(){
            div = $("div#page");

            // Nav form
            $(".nav form", div)
                .on("submit", function(e) {
                    e.preventDefault();
                });

            // List forms
            $(".inside form", div)
                .on("submit", function(e) {
                    e.preventDefault();
                });

            $("button[name='new']", div)
                .on("click", function(){
                    location.href = "/admin/user/new";
                });

            // Info Update
            $("form[name='update']", div)
                .on("submit", function(e){

                    e.preventDefault();

                    var form = $(this);

                    var site_ids = [];
                    $("input[name='site[]']:checked", form).each(function(){
                        site_ids.push($(this).val());
                    });

                    Core.ajax({
                        url: form.attr("action"),
                        data: {
                            "email":     $("input[name='email']", form).val(),
                            "status_id": $("select[name='status']", form).val(),
                            "sites":     site_ids.join(",")
                        },
                        success: function(response) {
                            if (response.status === 'good') {
                                CoreDialog.alert("User info has been updated", null, "good");
                            } else {
                                CoreDialog.error(response.message || "User info could not be updated");
                            }

                            $("div.error", form).hide();
                            $("label.error", form).removeClass("error");

                            if (response && response.errors) {
                                for (var k in response.errors) {
                                    $("div[name='" + k + "']", form)
                                        .text(response.errors[k])
                                        .show();

                                    $("label[name='" + k + "']", form)
                                        .addClass("error");
                                }
                            }
                        },
                        error: function(response) {
                            alert("There was a problem saving your user info");
                        }
                    });
                });

            // Change Password
            $("form[name='update-password']", div)
                .on("submit", function(e){

                    e.preventDefault();

                    var form = $(this);

                    Core.ajax({
                        url: form.attr("action"),
                        data: {
                            "password":            $("input[name='password']", form).val(),
                            "password_salt":       $("input[name='password_salt']", form).val(),
                            "password_hashmethod": $("select[name='hashmethod']", form).val(),
                            "password_cost":       $("input[name='password_cost']", form).val()
                        },
                        success: function(response) {
                            if (response.status === 'good') {
                                CoreDialog.alert("User password has been updated", null, "good");
                            } else {
                                if (response.message && response.message.length) {
                                    alert(response.message);
                                }
                            }

                            $("div.error", form).hide();
                            $("label.error", form).removeClass("error");

                            if (response && response.errors) {

                                if (response.errors["password1"]) {
                                    response.errors["password"] = response.errors["password1"];
                                }
                                if (response.errors["password2"]) {
                                    response.errors["password"] = response.errors["password2"];
                                }

                                for (var k in response.errors) {
                                    $("div[name='" + k + "']", form)
                                        .text(response.errors[k])
                                        .show();

                                    $("label[name='" + k + "']", form)
                                        .addClass("error");
                                }
                            }
                        },
                        error: function(response) {
                            alert("There was a problem saving your user password");
                        }
                    });
                });

            // Roles
            $("form[name='roles']", div)
                .on("submit", function(e){

                    e.preventDefault();

                    var form = $(this);

                    var role_ids = [];
                    $("input[name='role[]']:checked", form).each(function(){
                        role_ids.push($(this).val());
                    });

                    Core.ajax({
                        url: form.attr("action"),
                        data: {
                            "roles":  role_ids.join(",")
                        },
                        success: function(response) {
                            if (response.status === 'good') {
                                alert("User roles have been saved", null, "good");
                            } else {
                                alert(response.message || "User roles could not be updated");
                            }
                        },
                        error: function(response) {
                            alert("There was a problem saving your user roles");
                        }
                    });
                });

            // Groups
            $("form[name='groups']", div)
                .on("submit", function(e){

                    e.preventDefault();

                    var form = $(this);

                    var group_ids = [];
                    $("input[name='group[]']:checked", form).each(function(){
                        group_ids.push($(this).val());
                    });

                    Core.ajax({
                        url: form.attr("action"),
                        data: {
                            "groups": group_ids.join(",")
                        },
                        success: function(response) {
                            if (response.status === 'good') {
                                alert("User groups have been saved", null, "good");
                            } else {
                                alert(response.message || "User groups could not be updated");
                            }
                        },
                        error: function(response) {
                            alert("There was a problem saving your user groups");
                        }
                    });
                });

            // Random
            $("button[name='random']", div)
                .on("click", function(e) {
                    e.preventDefault();
                    e.stopPropagation();
                    var form = $(this).closest("form");
                    Core.ajax({
                        url: "/admin/user/ajax/random",
                        success: function(response) {
                            if (response.status === 'good') {
                                $("input[name='password_salt']", form).val(response.random);
                            } else {
                                if (response.message && response.message.length) {
                                    CoreDialog.alert(response.message, null, "error");
                                }
                            }
                        },
                        error: function(response) {
                            alert("There was a problem generating a random string");
                        }
                    });
                });
        });

        return self;
    })();

</script>

<div id="page">

    <h3 class="header"><a href="/admin">Admin</a> / <a href="/admin/user">Users</a> / <?php echo htmlspecialchars($this->user->email); ?></h3>

    <?php $this->inc('admin/templates/sidebar'); ?>
    <div>
        <div class="nav">
            <div class="side">
                <form>
                    <button name="new" class="btn"><?php echo htmlspecialchars($this->locale->translate('New')); ?></button>
                </form>
            </div>
        </div>

        <div class="inside">
            <div class="box">
                <div class="table-head">
                    User Info
                </div>
                <form name="update" action="/admin/user/ajax/update/id:<?php echo $this->user->id; ?>">
                    <div class="table-body">
                        <div style="padding: 10px 0;">
                            <table width="100%">
                                <tr>
                                    <td width="175" align="right">
                                        <label name="email">Email</label>
                                        <div name="email" class="tiny error" style="display: none;"></div>
                                    </td>
                                    <td width="10"></td>
                                    <td>
                                        <input type="text" name="email" value="<?php echo htmlspecialchars($this->user->email); ?>" style="width: 300px;" />
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div style="padding: 0 0 10px 0;">
                            <table width="100%">
                                <tr>
                                    <td width="175" align="right">
                                        <label name="status">Status</label>
                                        <div name="status" class="tiny error" style="display: none;"></div>
                                    </td>
                                    <td width="10"></td>
                                    <td>
                                        <select name="status">
                                            <?php foreach ($this->all_statuses as $status): ?>
                                                <?php if ($status->id === $this->user->status_id): ?>
                                                    <option value="<?php echo $status->id; ?>" selected="selected"><?php echo htmlspecialchars(ucwords($status->name)); ?></option>
                                                <?php else: ?>
                                                    <option value="<?php echo $status->id; ?>"><?php echo htmlspecialchars(ucwords($status->name)); ?></option>
                                                <?php endif; ?>
                                            <?php endforeach; ?>
                                        </select>
                                    </td>
                                </tr>
                            </table>
                        </div>

                        <div style="padding: 0 0 10px 0;">
                            <table width="100%">
                                <tr>
                                    <td width="175" align="right">
                                        <label name="site">Sites</label>
                                        <div name="site" class="tiny error" style="display: none;"></div>
                                    </td>
                                    <td width="10"></td>
                                    <td>
                                        <ul>
                                            <?php foreach ($this->all_sites as $site): ?>
                                                <label>
                                                    <input type="checkbox" name="site[]" value="<?php echo $site->id; ?>"<?php if (in_array($site->id, $this->user->site_collection()->field('id'))) { echo 'checked="checked" '; } ?> />
                                                    <b><?php echo htmlspecialchars($site->name); ?></b>
                                                </label>
                                            <?php endforeach; ?>
                                        </ul>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                    <div class="table-foot">
                        <div class="padded">
                            <button class="good" style="margin-left: 177px;">Update</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="inside">
            <div class="box">
                <div class="table-head">
                    Change Password
                </div>
                <form name="update-password" action="/admin/user/ajax/update_password/id:<?php echo $this->user->id; ?>">
                    <div class="table-body">
                        <div style="padding: 10px 0;">
                            <table width="100%">
                                <tr>
                                    <td width="175" align="right">
                                        <label name="password">Password</label>
                                        <div name="password" class="tiny error" style="display: none;"></div>
                                    </td>
                                    <td width="10"></td>
                                    <td>
                                        <input type="password" name="password" value="" style="width: 300px;" />
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div style="padding: 0 0 10px 0;">
                            <table width="100%">
                                <tr>
                                    <td width="175" align="right">
                                        <label name="password_salt">Password Salt</label>
                                        <div name="password_salt" class="tiny error" style="display: none;"></div>
                                    </td>
                                    <td width="10"></td>
                                    <td>
                                        <input type="text" name="password_salt" value="" style="width: 600px;" />
                                        <button name="random">Generate Random</button>
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div style="padding: 0 0 10px 0;">
                            <table width="100%">
                                <tr>
                                    <td width="175" align="right">
                                        <label name="password_hashmethod">Password Hashmethod</label>
                                        <div name="password_hashmethod" class="tiny error" style="display: none;"></div>
                                    </td>
                                    <td width="10"></td>
                                    <td>
                                        <select name="hashmethod">
                                            <?php foreach ($this->password_hashmethods as $password_hashmethod): ?>
                                                <?php if ($password_hashmethod->id === $this->user->password_hashmethod): ?>
                                                    <option value="<?php echo $password_hashmethod->id; ?>" selected="selected"><?php echo htmlspecialchars($password_hashmethod->name); ?></option>
                                                <?php else: ?>
                                                    <option value="<?php echo $password_hashmethod->id; ?>"><?php echo htmlspecialchars($password_hashmethod->name); ?></option>
                                                <?php endif; ?>
                                            <?php endforeach; ?>
                                        </select>
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div style="padding: 0 0 10px 0;">
                            <table width="100%">
                                <tr>
                                    <td width="175" align="right">
                                        <label name="password_cost">Password Cost</label>
                                        <div name="password_cost" class="tiny error" style="display: none;"></div>
                                    </td>
                                    <td width="10"></td>
                                    <td>
                                        <input type="text" name="password_cost" value="<?php echo $this->user->password_cost; ?>" style="width: 100px;" />
                                        <span class="tiny">(The larger the number the longer it will take to login)</span>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                    <div class="table-foot">
                        <div class="padded">
                            <button class="good" style="margin-left: 177px;">Update</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="inside">
            <div class="box">
                <div class="table-head">
                    Groups
                </div>
                <form name="groups" action="/admin/user/ajax/update_groups/id:<?php echo $this->user->id; ?>">
                    <div class="table-body">
                        <ul>
                            <?php foreach ($this->all_groups as $group): ?>
                            <li>
                                <label>
                                    <input type="checkbox" name="group[]" value="<?php echo $group->id; ?>" <?php if (in_array($group->id, $this->user->acl_group_collection()->field('id'))) { echo 'checked="checked" '; } ?>/>
                                    <b><?php echo htmlspecialchars($group->name); ?></b>
                                    <?php if (0 && count($resources = $group->acl_role_collection()->acl_resource_collection())): ?>
                                        <span class="unbold">(<?php echo join(', ', $resources->field('name')); ?>)</span>
                                    <?php endif; ?>
                                </label>
                            </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                    <div class="table-foot">
                        <div class="padded">
                            <button class="good">Update</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="inside">
            <div class="box">
                <div class="table-head">
                    Roles
                </div>
                <form name="roles" action="/admin/user/ajax/update_roles/id:<?php echo $this->user->id; ?>">
                    <div class="table-body">
                        <ul>
                            <?php foreach ($this->all_roles as $role): ?>
                                <li>
                                    <label>
                                        <input type="checkbox" name="role[]" value="<?php echo $role->id; ?>" <?php if (in_array($role->id, $this->user->acl_role_collection()->field('id'))) { echo 'checked="checked" '; } ?>/>
                                        <div style="display: inline-block; margin-left: 5px;"><?php echo htmlspecialchars($role->name); ?></div>
                                        <?php if (0 && count($resources = $role->acl_resource_collection())): ?>
                                            <span class="unbold">(<?php echo join(', ', $resources->field('name')); ?>)</span>
                                        <?php endif; ?>
                                    </label>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                    <div class="table-foot">
                        <div class="padded">
                            <button class="good">Update</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<?php $this->inc('admin/templates/footer'); ?>