<?php $this->inc('admin/templates/header'); ?>

<script>
    (function(){
        var self = {},
            div;


        /**
         * Init
         */
        $(function(){
            div = $("div#page");

            // Nav form
            $(".nav form", div)
                .on("submit", function(e) {
                    e.preventDefault();
                });

            // List forms
            $(".inside form", div)
                .on("submit", function(e) {
                    e.preventDefault();
                });

            $("button[name='new']", div)
                .on("click", function(){
                    location.href = "/admin/user/new";
                });

            $("form[name='insert']", div)
                .on("submit", function(e){

                    e.preventDefault();
                    e.stopPropagation();

                    var form = $(this);

                    var site_ids = [];
                    $("input[name='site[]']:checked", form).each(function(){
                        site_ids.push($(this).val());
                    });

                    var role_ids = [];
                    $("input[name='role[]']:checked", form).each(function(){
                        role_ids.push($(this).val());
                    });

                    var group_ids = [];
                    $("input[name='group[]']:checked", form).each(function(){
                        group_ids.push($(this).val());
                    });

                    Core.ajax({
                        url: form.attr("action"),
                        data: {
                            "email":               $("input[name='email']", form).val(),
                            "status_id":           $("select[name='status']", form).val(),
                            "password":            $("input[name='password']", form).val(),
                            "password_salt":       $("input[name='password_salt']", form).val(),
                            "password_hashmethod": $("select[name='hashmethod']", form).val(),
                            "password_cost":       $("input[name='password_cost']", form).val(),
                            "sites":               site_ids.join(","),
                            "roles":               role_ids.join(","),
                            "groups":              group_ids.join(",")
                        },
                        success: function(response) {
                            if (response.status === 'good') {
                                location.href = "/admin/user/view/id:" + response.user.id;
                            } else {
                                alert(response.message || "User info could not be updated");
                            }

                            $("div.tiny.error", form)
                                .css("display", "none");

                            $("label.error", form)
                                .removeClass("error");

                            $("input", form)
                                .removeClass("error");

                            if (response.errors) {
                                if (response.errors.password1) {
                                    response.errors.password = response.errors.password1;
                                }

                                for (var k in response.errors) {
                                    $("div[name='" + k + "'].error", form)
                                        .html(response.errors[k])
                                        .css("display", "block");

                                    $("input[name='" + k + "']", form)
                                        .addClass("error");

                                    $("label[name='" + k + "']", form)
                                        .addClass("error");
                                }
                            }
                        },
                        error: function(response) {
                            alert("There was a problem saving your user info");
                        }
                    });
                });

            $("button[name='random']", div)
                .on("click", function(e) {
                    e.preventDefault();
                    e.stopPropagation();

                    var form = $(this).closest("form");
                    Core.ajax({
                        url: "/admin/user/ajax/random",
                        success: function(response) {
                            if (response.status === 'good') {
                                $("input[name='password_salt']", form).val(response.random);
                            } else {
                                CoreDialog.error(response.message || "User info could not be updated");
                            }
                        },
                        error: function(response) {
                            alert("There was a problem generating a random string");
                        }
                    });
                });
        });

        return self;
    })();

</script>

<div id="page">

    <h3 class="header"><a href="/admin">Admin</a> / <a href="/admin/user">Users</a> / New</h3>

    <?php $this->inc('admin/templates/sidebar'); ?>
    <div>
        <div class="nav">
            <div class="side">
                <form>
                    <button name="new" class="btn"><?php echo htmlspecialchars($this->locale->translate('New')); ?></button>
                </form>
            </div>
        </div>

        <div class="inside">
            <div class="box">
                <div class="table-head">
                    User Info
                </div>
                <form name="insert" action="/admin/user/ajax/insert">
                    <div class="table-body">
                        <div style="padding: 10px 0;">
                            <table width="100%">
                                <tr>
                                    <td width="175" align="right">
                                        <label name="email">Email</label>
                                        <div name="email" class="tiny error" style="display: none;"></div>
                                    </td>
                                    <td width="10"></td>
                                    <td>
                                        <input type="text" name="email" value="" style="width: 300px;" autocomplete="off" />
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div style="padding: 0 0 10px 0;">
                            <table width="100%">
                                <tr>
                                    <td width="175" align="right">
                                        <label name="status">Status</label>
                                        <div name="status" class="tiny error" style="display: none;"></div>
                                    </td>
                                    <td width="10"></td>
                                    <td>
                                        <select name="status">
                                            <?php foreach ($this->all_statuses as $status): ?>
                                                <option value="<?php echo $status->id; ?>"><?php echo htmlspecialchars(ucwords($status->name)); ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </td>
                                </tr>
                            </table>
                        </div>

                        <div style="padding: 10px 0;">
                            <table width="100%">
                                <tr>
                                    <td width="175" align="right">
                                        <label name="password">Password</label>
                                        <div name="password" class="tiny error" style="display: none;"></div>
                                    </td>
                                    <td width="10"></td>
                                    <td>
                                        <input type="password" name="password" value="" style="width: 300px;" autocomplete="off" />
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div style="padding: 0 0 10px 0;">
                            <table width="100%">
                                <tr>
                                    <td width="175" align="right">
                                        <label name="password_salt">Password Salt</label>
                                        <div name="password_salt" class="tiny error" style="display: none;"></div>
                                    </td>
                                    <td width="10"></td>
                                    <td>
                                        <input type="text" name="password_salt" value="" style="width: 600px;" autocomplete="off" />
                                        <button name="random" class="small">Generate Random</button>
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div style="padding: 0 0 10px 0;">
                            <table width="100%">
                                <tr>
                                    <td width="175" align="right">
                                        <label name="password_hashmethod">Password Hashmethod</label>
                                        <div name="password_hashmethod" class="tiny error" style="display: none;"></div>
                                    </td>
                                    <td width="10"></td>
                                    <td>
                                        <select name="hashmethod">
                                            <?php foreach ($this->password_hashmethods as $password_hashmethod): ?>
                                                <option value="<?php echo $password_hashmethod->id; ?>"><?php echo htmlspecialchars($password_hashmethod->name); ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div style="padding: 0 0 10px 0;">
                            <table width="100%">
                                <tr>
                                    <td width="175" align="right">
                                        <label name="password_cost">Password Cost</label>
                                        <div name="password_cost" class="tiny error" style="display: none;"></div>
                                    </td>
                                    <td width="10"></td>
                                    <td>
                                        <input type="text" name="password_cost" value="10" style="width: 100px;" autocomplete="off" />
                                        <span class="tiny">(The larger the number the longer it will take to login)</span>
                                    </td>
                                </tr>
                            </table>
                        </div>
                        <div style="padding: 0 0 10px 0;">
                            <table width="100%">
                                <tr>
                                    <td width="175" align="right">
                                        <label name="site">Sites</label>
                                        <div name="site" class="tiny error" style="display: none;"></div>
                                    </td>
                                    <td width="10"></td>
                                    <td>
                                        <ul>
                                            <?php foreach ($this->all_sites as $site): ?>
                                                <label>
                                                    <input type="checkbox" name="site[]" value="<?php echo $site->id; ?>" />
                                                    <b><?php echo htmlspecialchars($site->name); ?></b>
                                                </label>
                                            <?php endforeach; ?>
                                        </ul>
                                    </td>
                                </tr>
                            </table>
                        </div>

                        <div class="table-head-mid">
                            Groups
                        </div>

                        <div class="table-body">
                            <ul>
                                <?php foreach ($this->all_groups as $group): ?>
                                    <li>
                                        <label>
                                            <input type="checkbox" name="group[]" value="<?php echo $group->id; ?>" />
                                            <b><?php echo htmlspecialchars($group->name); ?></b>
                                            <?php if (0 && count($resources = $group->acl_role_collection()->acl_resource_collection())): ?>
                                                <span class="unbold">(<?php echo join(', ', $resources->field('name')); ?>)</span>
                                            <?php endif; ?>
                                        </label>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>

                        <div class="table-head-mid">
                            Roles
                        </div>

                        <div class="table-body">
                            <ul>
                                <?php foreach ($this->all_roles as $role): ?>
                                    <li>
                                        <label>
                                            <input type="checkbox" name="role[]" value="<?php echo $role->id; ?>" />
                                            <div style="display: inline-block; margin-left: 5px;"><?php echo htmlspecialchars($role->name); ?></div>
                                            <?php if (0 && count($resources = $role->acl_resource_collection())): ?>
                                                <span class="unbold">(<?php echo join(', ', $resources->field('name')); ?>)</span>
                                            <?php endif; ?>
                                        </label>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>

                    </div>
                    <div class="table-foot">
                        <div class="padded">
                            <input type="submit" class="good" value="Save" style="margin-left: 177px;" />
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

<?php $this->inc('admin/templates/footer'); ?>