<?php $this->inc('admin/templates/header'); ?>

<script>
    (function(){
        var self = {},
            div;

        /**
         * Init
         */
        $(function(){
            div = $("div#page");

            // Nav form
            $(".nav form", div)
                .on("submit", function(e) {
                    e.preventDefault();
                });

            // List forms
            $(".inside form", div)
                .on("submit", function(e) {
                    e.preventDefault();
                });

            $("button[name='new']", div)
                .on("click", function(){
                    location.href = "/admin/user/new";
                });

            $("button[name='edit']", div)
                .on("click", function(){
                    location.href = "/admin/user/edit/id:<?php echo $this->user->id; ?>";
                });

            // Roles
            $("form[name='roles']", div)
                .on("submit", function(e){

                    e.preventDefault();

                    var form = $(this);

                    var role_ids = [];
                    $("input[name='role[]']:checked", form).each(function(){
                        role_ids.push($(this).val());
                    });

                    Core.ajax({
                        url: form.attr("action"),
                        data: {
                            "roles":  role_ids.join(",")
                        },
                        success: function(response) {
                            if (response.status === 'good') {
                                alert("User roles have been saved", null, "good");
                            } else {
                                alert(response.message || "User roles could not be updated");
                            }
                        },
                        error: function(response) {
                            alert("There was a problem saving your user roles");
                        }
                    });
                });

            // Groups
            $("form[name='groups']", div)
                .on("submit", function(e){

                    e.preventDefault();

                    var form = $(this);

                    var group_ids = [];
                    $("input[name='group[]']:checked", form).each(function(){
                        group_ids.push($(this).val());
                    });

                    Core.ajax({
                        url: form.attr("action"),
                        data: {
                            "groups": group_ids.join(",")
                        },
                        success: function(response) {
                            if (response.status === 'good') {
                                alert("User groups have been saved", null, "good");
                            } else {
                                alert(response.message || "User groups could not be updated");
                            }
                        },
                        error: function(response) {
                            alert("There was a problem saving your user groups");
                        }
                    });
                });
        });

        return self;
    })();

</script>

<div id="page">

    <h3 class="header"><a href="/admin">Admin</a> / <a href="/admin/user">Users</a> / <?php echo htmlspecialchars($this->user->email); ?></h3>

    <?php $this->inc('admin/templates/sidebar'); ?>
    <div>
        <div class="nav">
            <div class="side">
                <form>
                    <button name="new" class="btn"><?php echo htmlspecialchars($this->locale->translate('New')); ?></button>
                    <button name="edit" class="btn"><?php echo htmlspecialchars($this->locale->translate('Edit')); ?></button>
                </form>
            </div>
        </div>

        <div class="inside">
            <div class="box">
                <div class="table-head">
                    User Info
                </div>
                <div class="table-body">
                    <div style="padding: 10px 0;">
                        <table width="100%">
                            <tr>
                                <td width="175" align="right">
                                    Email
                                </td>
                                <td width="10"></td>
                                <td>
                                    <div class="bold"><?php echo htmlspecialchars($this->user->email); ?></div>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <div style="padding: 0 0 10px 0;">
                        <table width="100%">
                            <tr>
                                <td width="175" align="right">
                                    Status
                                </td>
                                <td width="10"></td>
                                <td>
                                    <div class="bold"><?php echo htmlspecialchars(ucwords($this->user->user_status()->name)); ?></div>
                                </td>
                            </tr>
                        </table>
                    </div>

                    <div style="padding: 10px 0;">
                        <table width="100%">
                            <tr>
                                <td width="175" align="right">
                                    Password
                                </td>
                                <td width="10"></td>
                                <td>
                                    <div>&lt;Hidden&gt;</div>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <div style="padding: 0 0 10px 0;">
                        <table width="100%">
                            <tr>
                                <td width="175" align="right">
                                    Password Salt
                                </td>
                                <td width="10"></td>
                                <td>
                                    <div>&lt;hidden&gt;</div>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <div style="padding: 0 0 10px 0;">
                        <table width="100%">
                            <tr>
                                <td width="175" align="right">
                                    Password Hashmethod
                                </td>
                                <td width="10"></td>
                                <td>
                                    <div class="bold"><?php echo htmlspecialchars($this->user->user_hashmethod()->name); ?></div>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <div style="padding: 0 0 10px 0;">
                        <table width="100%">
                            <tr>
                                <td width="175" align="right">
                                    Password Cost
                                    <div class="id-error-password_cost tiny error" style="display: none;"></div>
                                </td>
                                <td width="10"></td>
                                <td>
                                    <div class="bold"><?php echo $this->user->password_cost; ?></div>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="inside">
            <div class="box">
                <div class="table-head">
                    User Groups
                </div>
                <form name="groups" action="/admin/user/ajax/update_groups/id:<?php echo $this->user->id; ?>">
                    <div class="table-body">
                        <ul>
                            <?php foreach ($this->all_groups as $group): ?>
                            <li>
                                <label>
                                    <input type="checkbox" name="group[]" value="<?php echo $group->id; ?>" <?php if (in_array($group->id, $this->user->acl_group_collection()->field('id'))) { echo 'checked="checked" '; } ?>/>
                                    <b><?php echo htmlspecialchars($group->name); ?></b>
                                    <?php if (0 && count($resources = $group->acl_role_collection()->acl_resource_collection())): ?>
                                        <span class="unbold">(<?php echo join(', ', $resources->field('name')); ?>)</span>
                                    <?php endif; ?>
                                </label>
                            </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                    <div class="table-foot">
                        <div class="padded">
                            <button class="good">Update</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="inside">
            <div class="box">
                <div class="table-head">
                    User Roles
                </div>
                <form name="roles" action="/admin/user/ajax/update_roles/id:<?php echo $this->user->id; ?>">
                    <div class="table-body">
                        <ul>
                            <?php foreach ($this->all_roles as $role): ?>
                                <li>
                                    <label>
                                        <input type="checkbox" name="role[]" value="<?php echo $role->id; ?>" <?php if (in_array($role->id, $this->user->acl_role_collection()->field('id'))) { echo 'checked="checked" '; } ?>/>
                                        <div style="display: inline-block; margin-left: 5px;"><?php echo htmlspecialchars($role->name); ?></div>
                                        <?php if (0 && count($resources = $role->acl_resource_collection())): ?>
                                            <span class="unbold">(<?php echo join(', ', $resources->field('name')); ?>)</span>
                                        <?php endif; ?>
                                    </label>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                    <div class="table-foot">
                        <div class="padded">
                            <button class="good">Update</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<?php $this->inc('admin/templates/footer'); ?>