<?php $this->inc('templates/header'); ?>

    <script>

        var page = {

            onload: function() {

            }
        };

        $(page.onload);

    </script>

    <?php $this->inc('account/templates/sidebar'); ?>

    <div class="box" style="margin: 0 0 0 200px; display: block; width: 600px;">
        <div class="regular-head">Account Summary</div>
        <div class="regular-body">
            <table style="margin: 10px 0;">
                <tr>
                    <td width="150" align="right">
                        <label>Email Address</label>
                    </td>
                    <td width="10">&nbsp;</td>
                    <td>
                        <a href="/account/email"><?php echo htmlspecialchars(neoform\auth::instance()->user()->email); ?></a>
                    </td>
                </tr>
            </table>
            <table style="margin: 10px 0;">
                <tr>
                    <td width="150" align="right">
                        <label>Password</label>
                    </td>
                    <td width="10">&nbsp;</td>
                    <td>
                        <a href="/account/password">[Change Password]</a>
                    </td>
                </tr>
            </table>
            <table style="margin: 10px 0;">
                <tr>
                    <td width="150" align="right">
                        <label>Account Start Date</label>
                    </td>
                    <td width="10">&nbsp;</td>
                    <td>
                        <?php echo htmlspecialchars(neoform\auth::instance()->user_date()->created_on->format('D M j, Y')); ?>
                    </td>
                </tr>
            </table>
        </div>
    </div>

<?php $this->inc('templates/footer'); ?>