<?php $this->inc('admin/templates/header'); ?>

<script>
var page = {
    onload: function() {
        page.div = $("#page");
    }
};

$(page.onload);

</script>

<div id="page">

    <h3 class="header">Admin</h3>

    <?php $this->inc('admin/templates/sidebar'); ?>
    <div>
        <div class="inside">

            Stuffs goes here

        </div>
    </div>
</div>

<?php $this->inc('admin/templates/footer'); ?>