<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <title><?php echo htmlspecialchars($this->meta_title ? $this->meta_title : core::config()['core']['site_name']); ?></title>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <?php if ($this->meta_description): ?>
            <meta name="description" content="<?php echo htmlspecialchars($this->meta_description); ?>" />
        <?php endif; ?>
        <?php if ($this->meta_keywords): ?>
            <meta name="keywords" content="<?php echo htmlspecialchars($this->meta_keywords); ?>" />
        <?php endif; ?>
        <?php if ($this->canonical_url): ?>
            <link rel="canonical" href="<?php echo core::http()->server('url') . $this->canonical_url; ?>">
        <?php endif; ?>

        <!-- <link rel="shortcut icon" href="/static/favicon.ico" /> -->

        <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
        <link rel="stylesheet" type="text/css" href="/public/css/Core.css" media="all" />
        <link rel="stylesheet" type="text/css" href="/public/css/main.css" media="all" />
        <script type="text/javascript" src="/public/js/Core.js"></script>
        <script type="text/javascript" src="/public/js/spinner.js"></script>

        <!-- Dialog -->
        <link rel="stylesheet" type="text/css" href="/public/css/CoreDialog.css" media="all" />
        <script type="text/javascript" src="/public/js/CoreDialog.js"></script>

        <!-- Fonts -->
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
        <link href='https://fonts.googleapis.com/css?family=Oxygen:400,700,300' rel='stylesheet' type='text/css'>
    </head>
    <body>
        <div class="default">
            <div class="head">
                <div class="logo"><label><?php echo htmlspecialchars(core::config()['core']['site_name']); ?></label></div>
                <nav></nav>
            </div>
            <div class="main">
                <div class="box" style="width: 800px; margin: 30px auto;">
                    <?php if ($this->pre_header): ?>
                        <div class="regular-head"><?php echo htmlspecialchars($this->pre_header); ?></div>
                    <?php endif; ?>
                    <div class="regular-body" style="padding: 30px 15px; text-align: center;">
                        <h1>
                            <?php if ($this->header): ?>
                                <span class="liter"><?php echo htmlspecialchars($this->header); ?></span>
                            <?php endif; ?>
                        </h1>
                        <?php if ($this->body): ?>
                            <div style="font-size: 14px; line-height: 16px; font-weight: normal;">
                                <?php echo htmlspecialchars($this->body); ?>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            </div>
        </div>
        <footer>
            &copy; <?php echo date('Y'); ?> <?php echo htmlspecialchars(core::config()['core']['site_name']); ?>
        </footer>
        <!-- Page generated in <?php echo number_format((microtime(1) - APP_START_TIME) * 1000, 1); ?>ms using <?php echo number_format(memory_get_usage() / 1000, 2); ?> KB of ram -->
    </body>
</html>