<?php echo $this->inc('templates/header'); ?>

   <!--
   <script>
        $(function() {
             CoreDialog.confirm(
                "Are you sure you want to?",
                "Are You Sure?",
                [
                    {
                        "value": "yes",
                        "label": "Definitely",
                        "action": function(){ this.close(); },
                        "cssClass": "good",
                        "focused": true
                    },
                    {
                        "value": "no",
                        "label": "Cancel",
                        "action": function(){ this.close(); },
                        "cssClass": "error"
                    },
                    {
                        "value": "info",
                        "label": "Info",
                        "action": function(){ this.close(); },
                        "cssClass": "info"
                    },
                    {
                        "value": "special",
                        "label": "Special",
                        "action": function(){ this.close(); },
                        "cssClass": "special"
                    }
                ]
            );
        });
    </script>
    -->

    <div id="fileuploader">

        <div class="sidebar">

            <ul>
                <li>MP3s</li>
                <li>Photography</li>
                <li>Movies</li>
                <li>PDFs</li>
                <li>Soundtracks</li>
            </ul>

            <div class="sidebar-files on">Files</div>
            <div class="sidebar-files">Products</div>
        </div>

        <div class="browser-header">

            <div class="toolbar">
                <button>New Folder</button>
                <button>Upload File</button>
                <button class="right error">Delete</button>
            </div>

            <h2>Music Folder</h2>

            <div class="file-header">
                <table width="100%">
                   <tr>
                       <td>
                           Product
                       </td>
                       <td width="250">
                           Tags
                       </td>
                       <td width="100">
                           Status
                       </td>
                       <td width="100">
                           &nbsp;
                       </td>
                   </tr>
               </table>
            </div>
        </div>

        <form>
            <div class="browser">
                <ul class="products">
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="off">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                    <li class="on">
                        <table width="100%">
                           <tr>
                               <td width="20">
                                   <input type="checkbox" />
                               </td>
                               <td>
                                   Captain America
                               </td>
                               <td width="250">
                                   movies, action, comic book
                               </td>
                               <td width="100">
                                   Active
                               </td>
                               <td width="100">
                                   <button>Delete</button>
                               </td>
                           </tr>
                       </table>
                    </li>
                </ul>
            </div>
        </form>
    </div>

<?php echo $this->inc('templates/footer'); ?>