<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <title><?php echo htmlspecialchars($this->meta_title ? $this->meta_title : core::config()->system['site_name']); ?></title>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="description" content="<?php if ($this->meta_description) { echo htmlspecialchars($this->meta_description); } ?>" />
        <meta name="keywords" content="<?php if ($this->meta_keywords) { echo htmlspecialchars($this->meta_keywords); } ?><" />
        <!-- <link rel="shortcut icon" href="/static/favicon.ico" /> -->

        <?php if ($this->canonical_url): ?>
            <link rel="canonical" href="<?php echo core::http()->server('url') . $this->canonical_url; ?>">
        <?php endif; ?>

        <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
        <link rel="stylesheet" type="text/css" href="/public/css/Core.css" media="all" />
        <script type="text/javascript" src="/public/js/Core.js"></script>
        <script type="text/javascript" src="/public/js/spinner.js"></script>

        <!-- Dialog -->
        <link rel="stylesheet" type="text/css" href="/public/css/CoreDialog.css" media="all" />
        <script type="text/javascript" src="/public/js/CoreDialog.js"></script>

        <!-- Files -->
        <link rel="stylesheet" type="text/css" href="/public/css/files.css" media="all" />

        <!-- Fonts -->
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>

        <script>
            Core.ref("<?php echo core::http()->get_ref(); ?>");
        </script>
    </head>
    <body>
        <div class="account-files">
            <div class="head">
                <div class="logo"><label><?php echo htmlspecialchars(core::config()->system['site_name']); ?></label></div>
                <nav>
                    <ul>
                        <?php if (core::auth()->user_id): ?>
                        <li><a href="/account"><?php echo htmlspecialchars(core::auth()->user()->email); ?></a></li>
                        <li><a href="" name="logout">Logout</a></li>
                        <?php else: ?>
                        <li><a href="/account/login" name="login">Login</a></li>
                        <li><a href="/account/create" name="create-account">Create Account</a></li>
                        <?php endif; ?>
                    </ul>
                </nav>
            </div>
            <div class="main">