<?php $this->inc("templates/header"); ?>	

	<script type="text/javascript">	
		
		var page = {
			"onload": function() {					
				page.form = $("form[name='login']").submit(page.create);
				
				var email = $("input[name='email']", page.form).blur(page.validate_email);
					
				if (! email.val().length) {
					email.focus();
				}
				
				page.validate_email();
			},
			
			"create": function(e) {
				e.preventDefault();
			
				var submitButton = $("submit", page.form).attr('disabled', 'disabled');
				var errorDiv	 = $("div[name='login_error']", page.form);
										
				$.ajax({ 
					"url": "/account/ajax/insert?rc=<?php echo core::http()->get_ref(); ?>", 
					"data": {
						"email": 		$("input[name='email']", page.form).val(),
						"password1": 	$("input[name='password1']", page.form).val(),
						"password2": 	$("input[name='password2']", page.form).val()
					},
					"success": function(response) {
						submitButton.removeAttr('disabled');
						
						if (response.status === 'good') {
							location.href = location.href;
						} else {								
							if (response.message && response.message.length) {
								errorDiv.html(response.message).css('display', 'block');
							} else {
								errorDiv.html('There was a problem creating your account').css('display', 'block');
							}
							
							$(".error", page.form).css('display', 'none');
							
							if (response.errors) {
								for (var k in response.errors) {
									console.log($("div[name='" + k + "'].error", page.form));
									$("div[name='" + k + "'].error", page.form).html(response.errors[k]).css('display', 'block');
								}
							}
						}
			    	},
			    	"error": function(response) {
			    		errorDiv
			    			.html('There was a problem creating your account')
			    			.css('display', 'block');
			    			
			    		submitButton.removeAttr('disabled');	
			    	}
			    });
				
			},
			
			"validate_email": function(e) {
				var email = $("input[name='email']", page.form).val();
				
				if (email && email.length) {
					$.ajax({ 
						"url": "/account/ajax/check/email?rc=<?php echo core::http()->get_ref(); ?>", 
						"data": { 
							"email": email
						},
						"success": function(response) {
							if (response.status === 'good') {
								$("span[name='email_status']", page.form).html("<span class='good'>Available</span>");
							} else {
								$("span[name='email_status']", page.form).html("<span class='error'>" + response.message + "</span>");
							}
				    	}
				    });
				} else {
					$("span[name='email_status']", page.form).html('');
				}
			}
		};
		
		$(page.onload);
					
	</script>	
	
	<form name="login" style="margin: 0 auto; width: 600px; display: block;">	
		<div class="box">
		    <div class="regular-head">
			    Create Account
            </div>
            
            <div class="regular-body">
        		<div name="login_error" class="error"></div>
        	
        		<table>
        			<tr>
        				<td width="130" align="right">			
        					Email
        					<div name="email" class="tiny error" style="display: none;"></div>
        				</td>
        				<td width="10">&nbsp;</td>
        				<td>
        					<input type="text" name="email" style="width: 300px;" value="" />
        					<span name="email_status" class="tiny"></span>
        				</td>
        			</tr>
        			<tr>
        				<td width="130" align="right">
        					New Password
        					<div name="password1" class="tiny error" style="display: none;"></div>
        				</td>
        				<td width="10">&nbsp;</td>
        				<td>
        					<input type="password" name="password1" style="width: 300px;" value="" />
        				</td>
        			</tr>
        			<tr>
        				<td width="130" align="right">
        					Retype Password
        					<div name="password2" class="tiny error" style="display: none;"></div>
        				</td>
        				<td width="10">&nbsp;</td>
        				<td>
        					<input type="password" name="password2" style="width: 300px;" value="" />
        				</td>
        			</tr>
        		</table>
            </div>
            
    		<div class="regular-foot">
    			<input type="submit" value="Create Account" style="margin: 0 5px 0 140px;" />
    			<a href="/account/login" class="button">Member Login</a>
    		</div>					
		</div>	
	</form>
	
<?php $this->inc("templates/footer"); ?>