<?php $this->inc('templates/header'); ?>

<script type="text/javascript">

    var page = {
        "onload": function() {
            page.form = $("form[name='login']").submit(page.verify);
            $("input[name='email']", page.form).focus();
        },

        "verify": function(e) {
            e.preventDefault();

            var emailEl         = $("input[name='email']", page.form);
            var passwordEl      = $("input[name='password']", page.form);
            var messageEl       = $("div#message", page.form);
            var originalMessage = messageEl.text();

            $.ajax({
                "url": "<?php echo neoform\http::instance()->server('surl'); ?>account/ajax/login/verify?rc=<?php echo neoform\http::instance()->get_ref(); ?>",
                "data": {
                    "email":    $("input[name='email']", page.form).val(),
                    "password": $("input[name='password']", page.form).val(),
                    "remember": $("input[name='remember']", page.form).attr('checked') ? 1 : 0
                },
                "success": function(response) {
                    if (response.status === 'good') {
                        <?php if ($this->bounce): ?>
                            location.href = "/<?php echo htmlspecialchars($this->bounce); ?>";
                        <?php else: ?>
                            location.href = location.href;
                        <?php endif; ?>
                    } else {
                        emailEl.addClass('error');
                        passwordEl.addClass('error');

                        $("label[name='email']", page.form).addClass('error');
                        $("label[name='password']", page.form).addClass('error');

                        messageEl
                            .text(response.message || "There was a problem logging you in.")
                            .addClass("error")
                            .removeClass("info");

                        setTimeout(function() {
                            messageEl
                                .text(originalMessage)
                                .addClass("info")
                                .removeClass("error");

                            emailEl.removeClass('error');
                            passwordEl.removeClass('error');

                            $("label[name='email']", page.form).removeClass('error');
                            $("label[name='password']", page.form).removeClass('error');

                        }, 5500);
                    }
                }
            });
        }
    };

    $(page.onload);

</script>

<form name="login" style="margin: 0 auto; width: 600px; display: block;">
    <div class="box">
        <div class="regular-head">Login</div>
        <div class="regular-body">

            <?php if ($this->message): ?>
                <div class="padded info" id="message"><?php echo htmlspecialchars($this->message); ?></div>
            <?php else: ?>
                <div class="padded info" id="message">Please login to continue</div>
            <?php endif; ?>

            <table width="100%">

                <tr>
                    <td width="90" align="right">
                        <label name="email"><strong>Email</strong></label>
                    </td>
                    <td width="10">&nbsp;</td>
                    <td>
                        <input type="text" name="email" class="h2" style="width: 375px; font-size: 14px; line-height: 18px; padding: 5px 8px;" tabindex="1" />
                    </td>
                </tr>
                <tr>
                    <td width="90" align="right">
                        <label name="password"><strong>Password</strong></label>
                    </td>
                    <td width="10">&nbsp;</td>
                    <td>
                        <input type="password" name="password" class="h2" style="width: 220px; font-size: 14px; line-height: 18px; padding: 5px 8px;" tabindex="2" />
                        &nbsp;
                        <a href="/account/passwordretreive" class="button">Forgot Your Password?</a>
                    </td>
                </tr>
            </table>
        </div>
        <div class="regular-foot">
            <input type="submit" value="Login &raquo;" tabindex="4" style="margin: 3px 10px 5px 100px;" />
            <input type="checkbox" name="remember" id="login_remember" tabindex="3" /> <label for="login_remember">Keep me logged in</label>
        </div>
    </div>
</form>

<?php $this->inc('templates/footer'); ?>