<?php $this->inc('templates/header'); ?>

    <script>

        var page = {

            "onload": function() {
                page.form = $("form[name='password']")
                    .on("submit", page.submit);
            },

            "submit": function(e) {
                e.preventDefault();

                var save_button = $("input[name='change_password']", page.form);
                save_button.attr('disabled', 'disabled');

                $('.tiny.error').css('display', 'none').html('');

                Core.ajax({
                    "url": "/account/password/update",
                    "data": {
                        "current_password": $("input[name='current_password']", page.form).val(),
                        "password1":        $("input[name='password1']", page.form).val(),
                        "password2":        $("input[name='password2']", page.form).val()
                    },
                    "success": function(response) {

                        if (response && response.status === 'good') {
                            $("input[name='current_password']", page.form).val(''),
                            $("input[name='password1']", page.form).val(''),
                            $("input[name='password2']", page.form).val('')

                            alert("Your password has been updated");
                        } else {
                            alert(response.message || "Your password could not be updated");

                            if (response && response.errors) {
                                for (var k in response.errors) {
                                    $('.id-error-' + k, page.form).html(response.errors[k]).css('display', 'block');
                                }
                            }
                        }
                        save_button.removeAttr('disabled');
                    },
                    "error": function(response) {
                        console.log(response);
                        save_button.removeAttr('disabled');
                    }
                });
            }
        };

        $(page.onload);

    </script>

    <?php $this->inc('account/templates/sidebar'); ?>

    <form name="password" style="margin: 0 0 0 200px; display: block; width: 600px;">
        <div class="box">
            <div class="regular-head">Change Password</div>
            <div class="regular-body">
                <table>
                    <tr>
                        <td width="150" align="right">
                            Current Password
                            <div class="id-error-current_password tiny error" style="display: none;"></div>
                        </td>
                        <td width="10">&nbsp;</td>
                        <td>
                            <?php if ($this->forgotten): ?>
                                <input type="password" name="current_password" style="width: 250px;" value="<?php echo htmlspecialchars($this->forgotten); ?>" readonly="readonly" />
                            <?php else: ?>
                                <input type="password" name="current_password" style="width: 250px;" value="" />
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <td width="150" align="right">
                            New Password
                            <div class="id-error-password1 tiny error" style="display: none;"></div>
                        </td>
                        <td width="10">&nbsp;</td>
                        <td>
                            <input type="password" name="password1" style="width: 250px;" value="" />
                        </td>
                    </tr>
                    <tr>
                        <td width="150" align="right">
                            Re-type New Password
                            <div class="id-error-password2 tiny error" style="display: none;"></div>
                        </td>
                        <td width="10">&nbsp;</td>
                        <td>
                            <input type="password" name="password2" style="width: 250px;" value="" />
                        </td>
                    </tr>
                </table>
            </div>
            <div class="regular-foot">
                <div style="margin: 0 0 0 160px;">
                    <input type="submit" value="Update" name="change_password" style="font-size: 15px;" />
                </div>
            </div>
        </div>
    </form>

<?php $this->inc('templates/footer'); ?>