<?php $this->inc("templates/header"); ?>

    <script type="text/javascript">

        var page = {
            "onload": function() {
                page.form = $("form[name='lost-password']").on("submit", page.send);
                $("input[name='email']", page.form).focus();
            },

            "send": function(e) {
                e.preventDefault();

                $.ajax({
                    "url": "<?php echo core::http()->server('surl'); ?>account/ajax/password_lost?rc=<?php echo core::http()->get_ref(); ?>",
                    "data": {
                        "email": $("input[name='email']", page.form).val()
                    },
                    "success": function(response) {
                        var err = $(".message", page.form);
                        if (response && response.status === 'good') {
                            err.removeClass('error');
                            alert("Please check your email. You have been sent a link to reset your password.");
                        } else {
                            err.css('display', 'block');
                            err.addClass('error');
                            if (response && response.message) {
                                err.html(response.message);
                            } else {
                                err.html('There was a problem requesting a new password, please make sure your email address is correct.');
                            }
                        }
                    }
                });
            }
        };

        $(page.onload);

    </script>

    <form name="lost-password" style="margin: 0 auto; width: 600px; display: block;">

        <div class="box">
            <div class="regular-head">
                Password Reset
            </div>

            <div class="regular-body">

                <div class="message">Please enter your email address. We will send you a verification link in order to reset your password.</div>

                <table width="100%">
                    <tr>
                        <td width="90" align="right">
                            Email
                        </td>
                        <td width="10">&nbsp;</td>
                        <td>
                            <input type="text" name="email" class="h1" style="width: 375px;" tabindex="1" />
                        </td>
                    </tr>
                </table>
            </div>

            <div class="regular-foot">
                <input type="submit" value="Reset Password &raquo;" name="login" class="good" tabindex="2" style="margin: 0 0 0 100px;" />
                <a href="/account/login" class="button">Member Login</a>
            </div>
        </div>
    </form>

<?php $this->inc("templates/footer"); ?>