<?php $this->inc("templates/header"); ?>

    <script type="text/javascript">

        var page = {
            "onload": function() {
                page.form = $("form[name='lost-password']").on("submit", page.send);
                $("input[name='email']", page.form).focus();
            },

            "send": function(e) {
                e.preventDefault();

                var messageEl       = $(".message", page.form);
                var originalMessage = messageEl.text();

                Core.ajax({
                    "url": "<?php echo neoform\core::http()->server('surl'); ?>account/ajax/password_lost",
                    "data": {
                        "email": $("input[name='email']", page.form).val()
                    },
                    "success": function(response) {
                        if (response && response.status === 'good') {
                            messageEl
                                .addClass("info")
                                .removeClass("error");
                            alert("Please check your email. You have been sent a link to reset your password.");
                        } else {
                            messageEl
                                .addClass("error")
                                .removeClass("info")
                                .html(response.message || "There was a problem requesting a new password, please make sure your email address is correct.");

                            $("input[name='email']", page.form)
                                .addClass("error");

                            $("label[name='email']", page.form)
                                .addClass("error");

                            setTimeout(function(){
                                messageEl
                                    .text(originalMessage)
                                    .addClass("info")
                                    .removeClass("error");

                                $("input[name='email']", page.form)
                                    .removeClass("error");

                                $("label[name='email']", page.form)
                                    .removeClass("error");

                            }, 3500);
                        }
                    }
                });
            }
        };

        $(page.onload);

    </script>

    <form name="lost-password" style="margin: 0 auto; width: 600px; display: block;">

        <div class="box">
            <div class="regular-head">
                Password Reset
            </div>

            <div class="regular-body">

                <div class="padded info message">Please enter your email address. We will send you a verification link in order to reset your password.</div>

                <table width="100%">
                    <tr>
                        <td width="90" align="right">
                            <label name="email"><strong>Email</strong></label>
                        </td>
                        <td width="10">&nbsp;</td>
                        <td>
                            <input type="text" name="email" style="width: 375px; font-size: 14px; line-height: 18px; padding: 5px 8px; margin: 5px 0 10px 0;" tabindex="1" />
                        </td>
                    </tr>
                </table>
            </div>

            <div class="regular-foot">
                <input type="submit" value="Reset Password &raquo;" name="login" class="good" tabindex="2" style="margin: 0 0 0 100px;" />
                <a href="/account/login" class="button">Member Login</a>
            </div>
        </div>
    </form>

<?php $this->inc("templates/footer"); ?>