<div style="position: absolute; top: 10px; left: 5px; width: 190px;">
    <div class="box">
        <div class="regular-body">
            <?php
                $slug1 = neoform\http::instance()->slug(1);
                $slug2 = neoform\http::instance()->slug(2);
            ?>
            <ul class="top">
                <li class="<?php echo $slug2 === 'dashboard' ? ' active' : ''; ?>">
                    <a href="/account">Home</a>
                </li>
                <li class="<?php echo $slug2 === 'info' || $slug2 === 'email' || $slug2 === 'password' ? ' active' : ''; ?>">
                    <ul>
                        <li<?php echo $slug2 === 'email' ? ' class="active"' : ''; ?>><a href="/account/email">Change Email</a></li>
                        <li<?php echo $slug2 === 'password' ? ' class="active"' : ''; ?>><a href="/account/password">Change Password</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>