<?php $this->inc('admin/templates/header'); ?>

<script>
    (function() {
        var self = {},
            div;

        /**
         * Init
         */
        $(function(){
            div = $("div#page");

            // Nav form
            $(".nav form", div)
                .on("submit", function(e) {
                    e.preventDefault();
                });

            // List forms
            $(".inside form", div)
                .on("submit", function(e) {
                    e.preventDefault();
                });

            $("button[name='new']", div)
                .on("click", function(){
                    location.href = "/admin/user/new";
                });
        });

        return self;
    })();
</script>

<div id="page">

    <h3 class="header"><a href="/admin">Admin</a> / Users</h3>

    <?php $this->inc('admin/templates/sidebar'); ?>
    <div>
        <div class="nav">
            <div class="side">
                <form>
                    <button name="new" class="btn"><?php echo htmlspecialchars($this->locale->translate('New')); ?></button>
                </form>
            </div>
        </div>

        <div class="inside">

            <?php if ($this->users): ?>

                <div class="counts">
                    Total Users: <?php echo number_format($this->total); ?>
                </div>

                <div class="box">
                    <div class="table-head">
                        <table width="100%" cellspacing="0" cellpadding="0">
                            <tr>
                                <td width="100">
                                    <a href="/admin/user<?php echo $this->sorter->get_params('id'); ?>">ID</a>
                                </td>
                                <td>
                                    <a href="/admin/user<?php echo $this->sorter->get_params('email'); ?>">Email</a>
                                </td>
                                <td width="170">
                                    Sites
                                </td>
                                <td width="100">
                                    <a href="/admin/user<?php echo $this->sorter->get_params('status_id'); ?>">Status</a>
                                </td>
                                <td width="160">
                                    <a href="/admin/user<?php echo $this->sorter->get_params('created_on'); ?>">Created On</a>
                                </td>
                                <td width="160">
                                    <a href="/admin/user<?php echo $this->sorter->get_params('last_login'); ?>">Last Login</a>
                                </td>
                            </tr>
                        </table>
                    </div>

                    <form>
                        <div class="table-body">
                            <ul id="users">
                                <?php foreach ($this->users as $user): ?>
                                    <li>
                                        <table width="100%" cellspacing="0" cellpadding="0">
                                            <tr>
                                                <td width="100">
                                                    <?php echo $user->id; ?>
                                                </td>
                                                <td>
                                                    <a href="/admin/user/view/id:<?php echo $user->id; ?>"><?php echo htmlspecialchars($user->email); ?></a>
                                                </td>
                                                <td width="170">
                                                    <?php echo htmlspecialchars(join(',', $user->site_collection()->field('name'))); ?>
                                                </td>
                                                <td width="100">
                                                    <?php echo htmlspecialchars($user->user_status()->name); ?>
                                                </td>
                                                <td width="160">
                                                    <?php echo $user->user_date() ? $user->user_date()->created_on : '--'; ?>
                                                </td>
                                                <td width="160">
                                                    <?php echo $user->user_date() ? $user->user_date()->last_login : '--'; ?>
                                                </td>
                                            </tr>
                                        </table>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </form>
                    <div class="table-foot">
                        Page
                        <?php
                            $this->inc(
                                'templates/pagination',
                                [
                                    'url'          => '/admin/user' . $this->sorter->get_params(),
                                    'current_page' => (int) $this->page,
                                    'page_count'   => $this->total > 1 ? ceil($this->total / $this->per_page) : 1,
                                    'link_count'   => 5,
                                    'next'         => true,
                                ]
                            );
                        ?>
                    </div>
                </div>

            <?php else: ?>

                <form>
                    <div class="table-body">
                        <div class="empty">No users to show</div>
                    </div>
                </form>

            <?php endif; ?>
        </div>
    </div>
</div>

<?php $this->inc('admin/templates/footer'); ?>