                </div>
            </div>
        <footer>
    		&copy; <?php echo date('Y'); ?> <?php echo htmlspecialchars(core::config()->system['site_name']); ?>
		</footer>
		<!--Page generated in <strong><?php echo number_format(microtime(1) - APP_START_TIME, 4); ?></strong> seconds using <strong><?php echo number_format(memory_get_usage() / 1000, 2); ?></strong> KB of memory -->
	</body>
</html>