<div class="pages">
	<?php echo $this->locale->translate('Results'); ?>:
	<?php if ($count < $per_page): ?>
		<b><?php echo number_format(($page - 1) * ($per_page) + 1); ?></b>-<b><?php echo number_format(($page - 1) * $per_page + $count); ?></b>
	<?php else: ?>
		<b><?php echo number_format(($page - 1) * ($per_page) + 1); ?></b>-<b><?php echo number_format($page * $per_page); ?></b>
	<?php endif; ?>
	<?php echo $this->locale->translate('out of'); ?>
	<b><?php echo number_format($total_count); ?></b>
	&nbsp;&nbsp;
	<?php echo $this->locale->translate('Page'); ?>
	<?php
		$page_count = $total_count > 1 ? ceil($total_count / $per_page) : 1;
		if ($page_count > 10) {
			$page_count = 10;
		}
		$this->inc(
			'templates/pagination',
			[
				'url' 				=> $url,
				'current_page' 		=> (int) $page,
				'page_count' 		=> $page_count,
				'link_count' 		=> 5,
				'next'				=> true,
			]
		);
	?>
</div>