<?php $this->inc('admin/templates/header'); ?>

<script>
    (function(){
        var self = {},
            div,
            $divResources;

        var menuAdd = function($holder, options, selected) {

            var $select   = $("<select>");
            var $children = $("<div>");

            if (! $.isEmptyObject(options)) {

                $("<option>").appendTo($select);

                for (var k in options) {
                    var $option = $("<option>")
                        .attr("value", k)
                        .text(options[k]);

                    $select.append($option);

                    if (k == selected) {
                        $option.prop("selected", true);
                    }
                }
            } else {
                $select
                    .prop("disabled", true)
                    .append(
                        $("<option>")
                    );
            }

            $select.on("change", menuChange);

            $holder
                .append($select)
                .append($children);

            return $children;
        };

        var menuChange = function(e) {
            var $this = $(this);
            var $children = $this.next("div");
            $children.empty();

            Core.ajax({
                "url": "/admin/acl/resource/ajax/children/id:" + $this.val(),
                "success": function(response) {
                    if (response.status === 'good') {
                        menuAdd(
                            $children,
                            response.children
                        );
                    } else {
                        CoreDialog.error("Error loading child resources");
                    }
                }
            });
        };

        var getSelectedParent = function() {
            var $select = $("select", $divResources);
            while (1) {
                var $next = $("select", $select.next("div"));
                if ($next.length && $next.val()) {
                    $select = $next;
                } else {
                    return $select.val();
                }
            }
        };

        $(function() {
            div = $("div#page");

            $divResources = $("div[name='resources']", div);

            // Nav form
            $(".nav form", div)
                .on("submit", function(e) {
                    e.preventDefault();
                });

            // List forms
            $(".inside form", div)
                .on("submit", function(e) {
                    e.preventDefault();
                });

            $("button[name='new']", div)
                .on("click", function(){
                    location.href = "/admin/acl/resource/new/id:<?php echo $this->resource->id; ?>";
                });

            $("button[name='move']", div)
                .on("click", function(e){
                    e.preventDefault();
                    CoreDialog.showUrl("/admin/acl/resource/ajax/dialog/move/id:<?php echo $this->resource->id; ?>");
                });

            // Update
            $("form[name='update']", div)
                .on("submit", function(e){

                    e.preventDefault();

                    var form = $(this);

                    Core.ajax({
                        url: form.attr("action"),
                        data: {
                            "name": $("input[name='name']", form).val(),
                            "parent_id": getSelectedParent()
                        },
                        success: function(response) {
                            if (response.status === 'good') {
                                CoreDialog.alert("Resource info has been saved", null, "good");
                            } else {
                                CoreDialog.alert(response.message || "Resource info has not be updated");
                            }

                            $(".error", form).hide();

                            if (response && response.errors) {
                                for (var k in response.errors) {
                                    $(".id-error-" + k, form).html(response.errors[k]).show();
                                }
                            }
                        },
                        error: function(response) {
                            alert("There was a problem saving your resource info");
                        }
                    });
                });

            // Roles
            $("form[name='roles']", div)
                .on("submit", function(e){

                    e.preventDefault();

                    var form = $(this);

                    var role_ids = [];
                    $("input[name='role[]']:checked", form).each(function(){
                        role_ids.push($(this).val());
                    });

                    Core.ajax({
                        url: form.attr("action"),
                        data: {
                            "roles": role_ids.join(",")
                        },
                        success: function(response) {
                            if (response.status === 'good') {
                                CoreDialog.alert("Resource roles have been saved", null, "good");
                            } else {
                                CoreDialog.alert(response.message || "Resource roles could not be updated");
                            }

                            $(".error", form).hide();

                            if (response && response.errors) {
                                for (var k in response.errors) {
                                    $(".id-error-" + k, form).html(response.errors[k]).show();
                                }
                            }
                        },
                        error: function(response) {
                            alert("There was a problem saving your resource roles");
                        }
                    });
                });

            <?php
                $ancestors = $this->resource->ancestors();
                $ancestor_ids = [];
                foreach ($ancestors as $ancestor) {
                    $ancestor_ids[] = $ancestor->id;
                }
                $order_by = [ 'name' => neoform\entity\dao::SORT_ASC, ];
            ?>

            var $holder = menuAdd(
                $divResources,
                <?php echo json_encode($this->root_resources->field('name', 'id')); ?>,
                <?php echo isset($ancestor_ids[0]) ? $ancestor_ids[0] : 'null'; ?>
            );

            <?php foreach ($this->resource->ancestors() as $i => $resource): ?>
                $holder = menuAdd(
                    $holder,
                    <?php echo json_encode($resource->child_acl_resource_collection($order_by)->field('name', 'id')); ?>,
                    <?php echo isset($ancestor_ids[$i+1]) ? $ancestor_ids[$i+1] : 'null'; ?>
                );
            <?php endforeach; ?>
        });

        return self;
    })();

</script>

<style>
    div[name='resources'] select {
        font-size: 14px;
        line-height: 26px;
        display: inline-block;
        margin: 6px 2px;
    }
    div[name='resources'] div {
        display: inline-block;
    }
</style>

<div id="page">

    <h3 class="header">
        <a href="/admin"><?php echo htmlspecialchars($this->locale->translate('Admin')); ?></a>
        / <a href="/admin/acl"><?php echo htmlspecialchars($this->locale->translate('ACL')); ?></a>
        / <a href="/admin/acl/resource"><?php echo htmlspecialchars($this->locale->translate('Resources')); ?></a>
        / <?php echo htmlspecialchars($this->resource->name); ?>
    </h3>

    <?php $this->inc('admin/templates/sidebar'); ?>

    <div>
        <div class="nav">
            <div class="side">
                <form>
                    <button name="new" class="btn"><?php echo htmlspecialchars($this->locale->translate('New')); ?></button>
                    <button name="move" class="btn"><?php echo htmlspecialchars($this->locale->translate('Move')); ?></button>
                    <button name="delete" class="btn error"><?php echo htmlspecialchars($this->locale->translate('Delete')); ?></button>
                </form>
            </div>
        </div>

        <div style="padding: 0 5px;">
            <h3>
                <a href="/admin/acl/resource">public</a>
                <?php if ($this->resource): ?>
                    <?php foreach ($this->resource->ancestors() as $resource): ?>
                        / <a href="/admin/acl/resource/<?php echo $resource->id; ?>"><?php echo htmlspecialchars($resource->name); ?></a>
                    <?php endforeach; ?>
                    / <a href="/admin/acl/resource/<?php echo $this->resource->id; ?>"><?php echo htmlspecialchars($this->resource->name); ?></a>
                <?php endif; ?>
            </h3>
        </div>

        <div class="inside">
            <div class="box">
                <div class="table-head">
                    <?php echo htmlspecialchars($this->locale->translate('Resource')); ?>
                </div>
                <form name="update" action="/admin/acl/resource/ajax/update/id:<?php echo $this->resource->id; ?>">
                    <div class="table-body">
                        <div style="padding: 10px 0;">
                            <table width="100%">
                                <tr>
                                    <td width="175" align="right">
                                        <label name="name">Name</label>
                                        <div name="name" class="tiny error" style="display: none;"></div>
                                    </td>
                                    <td width="10"></td>
                                    <td>
                                        <input type="text" name="name" value="<?php echo htmlspecialchars($this->resource->name); ?>" style="width: 300px;" />
                                    </td>
                                </tr>
                            </table>
                            <table width="100%">
                                <tr>
                                    <td width="175" align="right">
                                        <label name="parent_id">Parent</label>
                                        <div name="parent_id" class="tiny error" style="display: none;"></div>
                                    </td>
                                    <td width="10"></td>
                                    <td>
                                        <div name="resources" style="padding: 5px 10px 5px 0;"></div>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                    <div class="table-foot">
                        <button class="good" style="margin: 0 0 0 177px;">Update</button>
                    </div>
                </form>
            </div>
        </div>

        <div class="inside">
            <div class="box">
                <div class="table-head">
                    Roles
                </div>
                <form name="roles" action="/admin/acl/resource/ajax/update_roles/id:<?php echo $this->resource->id; ?>">
                    <div class="table-body">
                        <ul>
                            <?php foreach ($this->roles as $role): ?>
                                <li>
                                    <label>
                                        <input type="checkbox" name="role[]" value="<?php echo $role->id; ?>" <?php if (in_array($role->id, $this->resource->acl_role_collection()->field('id'))) { echo 'checked="checked" '; } ?>/>
                                        <b><?php echo htmlspecialchars($role->name); ?></b>
                                    </label>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                    <div class="table-foot">
                        <button class="good">Update</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

<?php $this->inc('admin/templates/footer'); ?>