<?php $this->inc('admin/templates/header'); ?>

<script>
    (function(){
        var self = {},
            div;

        $(function() {
            div = $("div#page");

            // Nav form
            $(".nav form", div)
                .on("submit", function(e) {
                    e.preventDefault();
                });

            // List forms
            $(".inside form", div)
                .on("submit", function(e) {
                    e.preventDefault();
                });

            $("button[name='new']", div)
                .on("click", function(){
                    location.href = "/admin/acl/resource/new<?php if ($this->resource) { echo "/id:{$this->resource->id}"; } ?>";
                });

            $("button[name='edit']", div)
                .on("click", function(){
                    location.href = "/admin/acl/resource/edit/id:<?php echo $this->resource->id; ?>";
                });

            // Roles
            $("form[name='roles']", div)
                .on("submit", function(e){

                    e.preventDefault();

                    var form = $(this);

                    var role_ids = [];
                    $("input[name='role[]']:checked", form).each(function(){
                        role_ids.push($(this).val());
                    });

                    Core.ajax({
                        url: form.attr("action"),
                        data: {
                            "roles": role_ids.join(",")
                        },
                        success: function(response) {
                            if (response.status === 'good') {
                                CoreDialog.alert("Resource roles have been saved", null, "good");
                            } else {
                                CoreDialog.alert(response.message || "Resource roles could not be updated");
                            }

                            $(".error", form).hide();

                            if (response && response.errors) {
                                for (var k in response.errors) {
                                    $(".id-error-" + k, form).html(response.errors[k]).show();
                                }
                            }
                        },
                        error: function(response) {
                            alert("There was a problem saving your resource roles");
                        }
                    });
                });
        });

        return self;
    })();

</script>

<div id="page">

    <h3 class="header">
        <a href="/admin"><?php echo htmlspecialchars($this->locale->translate('Admin')); ?></a>
        / <a href="/admin/acl"><?php echo htmlspecialchars($this->locale->translate('ACL')); ?></a>
        / <a href="/admin/acl/resource"><?php echo htmlspecialchars($this->locale->translate('Resources')); ?></a>
        / <?php echo htmlspecialchars($this->resource->name); ?>
    </h3>

    <?php $this->inc('admin/templates/sidebar'); ?>

    <div>
        <div class="nav">
            <div class="side">
                <form>
                    <button name="new" class="btn"><?php echo htmlspecialchars($this->locale->translate('New')); ?></button>
                    <button name="edit" class="btn"><?php echo htmlspecialchars($this->locale->translate('Edit')); ?></button>
                </form>
            </div>
        </div>

        <div style="padding: 0 5px;">
            <h3>
                <a href="/admin/acl/resource">public</a>
                <?php if ($this->resource): ?>
                    <?php foreach ($this->resource->ancestors() as $resource): ?>
                        / <a href="/admin/acl/resource/<?php echo $resource->id; ?>"><?php echo htmlspecialchars($resource->name); ?></a>
                    <?php endforeach; ?>
                    / <a href="/admin/acl/resource/<?php echo $this->resource->id; ?>"><?php echo htmlspecialchars($this->resource->name); ?></a>
                <?php endif; ?>
            </h3>
        </div>

        <div class="inside">
            <div class="box">
                <div class="table-head">
                    <?php echo htmlspecialchars($this->locale->translate('Resource')); ?>
                </div>
                <div class="table-body">
                    <div style="padding: 10px 0;">
                        <table width="100%">
                            <tr>
                                <td width="175" align="right">
                                    Name
                                </td>
                                <td width="10"></td>
                                <td>
                                    <div class="bold" style="padding: 5px 0;"><?php echo htmlspecialchars($this->resource->name); ?></div>
                                </td>
                            </tr>
                        </table>
                        <table width="100%">
                            <tr>
                                <td width="175" align="right">
                                    Parents
                                </td>
                                <td width="10"></td>
                                <td>
                                    <div style="padding: 5px 0;">
                                        <?php
                                            $links = [];
                                            foreach ($this->resource->ancestors() as $resource) {
                                                $links[] = "<b><a href=\"/admin/acl/resource/view/id:{$resource->id}\">{$resource->name}</a></b>";
                                            }
                                        ?>
                                        <?php if ($links): ?>
                                            <?php echo join(' > ', $links); ?>
                                        <?php else: ?>
                                            --
                                        <?php endif; ?>
                                    </div>
                                </td>
                            </tr>
                        </table>
                        <table width="100%">
                            <tr>
                                <td width="175" align="right">
                                    Slug
                                </td>
                                <td width="10"></td>
                                <td>
                                    <div class="bold" style="padding: 5px 0;"><?php echo htmlspecialchars($this->resource->slug()); ?></div>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="inside">
            <div class="box">
                <div class="table-head">
                    Roles
                </div>
                <form name="roles" action="/admin/acl/resource/ajax/update_roles/id:<?php echo $this->resource->id; ?>">
                    <div class="table-body">
                        <ul>
                            <?php foreach ($this->roles as $role): ?>
                                <li>
                                    <label>
                                        <input type="checkbox" name="role[]" value="<?php echo $role->id; ?>" <?php if (in_array($role->id, $this->resource->acl_role_collection()->field('id'))) { echo 'checked="checked" '; } ?>/>
                                        <b><?php echo htmlspecialchars($role->name); ?></b>
                                    </label>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                    <div class="table-foot">
                        <button class="good">Update</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

<?php $this->inc('admin/templates/footer'); ?>