<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <title><?php echo htmlspecialchars($this->meta_title ? $this->meta_title : core::config()['core']['site_name']); ?></title>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <?php if ($this->meta_description): ?>
            <meta name="description" content="<?php echo htmlspecialchars($this->meta_description); ?>" />
        <?php endif; ?>
        <?php if ($this->meta_keywords): ?>
            <meta name="keywords" content="<?php echo htmlspecialchars($this->meta_keywords); ?>" />
        <?php endif; ?>
        <?php if ($this->canonical_url): ?>
            <link rel="canonical" href="<?php echo core::http()->server('url') . $this->canonical_url; ?>">
        <?php endif; ?>

        <link rel="shortcut icon" href="#" />

        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
        <link rel="stylesheet" type="text/css" href="/public/css/Core.css" media="all" />
        <link rel="stylesheet" type="text/css" href="/public/css/main.css" media="all" />
        <script type="text/javascript" src="/public/js/Core.js"></script>
        <script type="text/javascript" src="/public/js/spinner.js"></script>

        <!-- Dialog -->
        <link rel="stylesheet" type="text/css" href="/public/css/CoreDialog.css" media="all" />
        <script type="text/javascript" src="/public/js/CoreDialog.js"></script>

        <!-- Fonts -->
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>

        <script>
            Core.ref("<?php echo core::http()->get_ref(); ?>");
            <?php if ($this->locale->get_default() !== $this->locale->get()): ?>
                Core.locale("<?php echo $this->locale->get(); ?>");
            <?php endif; ?>
        </script>
    </head>
    <body>
        <div class="default">
            <div class="head">
                <div class="logo"><label><?php echo htmlspecialchars(core::config()['core']['site_name']); ?></label></div>
                <nav>
                    <ul>
                        <?php if (core::auth()->logged_in()): ?>
                            <li><a href="<?php echo $this->locale->route('/account'); ?>"><?php echo htmlspecialchars(core::auth()->user()->email); ?></a></li>
                            <li><a href="<?php echo $this->locale->route('/account/logout'); ?>" name="logout"><?php echo htmlspecialchars($this->locale->translate('Logout', 'admin')); ?></a></li>
                        <?php else: ?>
                            <li><a href="<?php echo $this->locale->route('/account/login'); ?>" name="login"><?php echo htmlspecialchars($this->locale->translate('Login', 'admin')); ?></a></li>
                            <li><a href="<?php echo $this->locale->route('/account/create'); ?>" name="create-account"><?php echo htmlspecialchars($this->locale->translate('Create Account', 'admin')); ?></a></li>
                        <?php endif; ?>
                    </ul>
                </nav>
            </div>
            <div class="main">