<?php
    $s = core::http()->segments() + array(1 => null, 2 => null, 3 => null, ); //dirty little hack, don't tell anyone. shhhh.
?>
<div class="box inner sidebar">
    <ul>
        <li><a href="/admin/users">Users</a></li>
        <li><a href="/admin/groups">Groups</a></li>
        <li><a href="/admin/acl/roles">ACL Roles</a></li>
        <li><a href="/admin/acl/resources">ACL Resources</a></li>
        <li><a href="/admin/locale/messages">Translations</a></li>
    </ul>
</div>