<?php $this->inc('admin/templates/header'); ?>

<script>
    (function(){

        var self = {},
            div;

        /**
         * Init
         */
        $(function() {
            div = $("div#page");

            // Nav form
            $(".nav form", page.div)
                .on("submit", function(e) {
                    e.preventDefault();
                });

            // List forms
            $(".inside form", page.div)
                .on("submit", function(e) {
                    e.preventDefault();
                });

            $(".inside form button.edit", div)
                .on("click", function(e){
                    e.preventDefault();
                    location.href = "/admin/acl/role/edit/id:" + $(this).closest("li").data("id");
                });

            $("button[name='new']", page.div)
                .on("click", function(e){
                    e.preventDefault();
                    location.href = "/admin/acl/role/new";
                });
        });

        return self;
    })();
</script>

<div id="page">

    <h3 class="header"><a href="/admin">Admin</a> / <a href="/admin/acl">ACL</a> / Roles</h3>

    <?php $this->inc('admin/templates/sidebar'); ?>
    <div>
        <div class="nav">
            <div class="side">
                <form>
                    <button name="new" class="btn"><?php echo htmlspecialchars($this->locale->translate('New')); ?></button>
                </form>
            </div>
        </div>

        <div class="inside">

            <?php if ($this->roles): ?>

                <div class="counts">
                    Total Roles: <?php echo number_format($this->total); ?>
                </div>

                <div class="box">
                    <div class="table-head">
                        <table width="100%" cellspacing="0" cellpadding="0">
                            <tr>
                                <td width="60">
                                    &nbsp;
                                </td>
                                <td width="100">
                                    <a href="/admin/acl/role<?php echo $this->sorter->get_params('id'); ?>"
                                        <?php if ($this->sorter->get_order('id')) { echo 'class="sort-' . $this->sorter->get_order('id') . '"'; } ?>
                                        >ID</a>
                                </td>
                                <td width="250">
                                    <a href="/admin/acl/role<?php echo $this->sorter->get_params('name'); ?>"
                                        <?php if ($this->sorter->get_order('name')) { echo 'class="sort-' . $this->sorter->get_order('name') . '"'; } ?>
                                        >Name</a>
                                </td>
                                <td width="300">
                                    Resources
                                </td>
                                <td width="10">&nbsp;</td>
                                <td>
                                    Groups
                                </td>
                            </tr>
                        </table>
                    </div>

                    <form>
                        <div class="table-body">
                            <ul id="roles">
                                <?php foreach ($this->roles as $role): ?>
                                    <li data-id="<?php echo $role->id; ?>">
                                        <table width="100%" cellspacing="0" cellpadding="0">
                                            <tr>
                                                <td width="60">
                                                    <button name="edit" class="small edit" style="">Edit</button>
                                                </td>
                                                <td width="100">
                                                    <?php echo $role->id; ?>
                                                </td>
                                                <td width="250">
                                                    <a href="/admin/acl/role/view/id:<?php echo $role->id; ?>"><?php echo htmlspecialchars($role->name); ?></a>
                                                </td>
                                                <td width="300">
                                                    <?php
                                                        $links = [];
                                                        foreach ($role->acl_resource_collection() as $resource) {
                                                            $links[] = '<a href="/admin/acl/resource/view/id:' . $resource->id . '">' . htmlspecialchars($resource->slug()) . '</a>';
                                                        }
                                                    ?>
                                                    <?php if ($links): ?>
                                                        <?php echo join(', ', $links); ?>
                                                    <?php else: ?>
                                                        --
                                                    <?php endif; ?>
                                                </td>
                                                <td width="10">&nbsp;</td>
                                                <td>
                                                    <?php
                                                        $links = [];
                                                        foreach ($role->acl_group_collection() as $group) {
                                                            $links[] = '<a href="/admin/acl/group/view/id:' . $group->id . '">' . htmlspecialchars($group->name) . '</a>';
                                                        }
                                                    ?>
                                                    <?php if ($links): ?>
                                                        <?php echo join(', ', $links); ?>
                                                    <?php else: ?>
                                                        --
                                                    <?php endif; ?>
                                                </td>
                                            </tr>
                                        </table>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </form>
                    <div class="table-foot">
                        Page
                        <?php
                            $this->inc(
                                'templates/pagination',
                                [
                                    'url'          => '/admin/acl/role' . $this->sorter->get_params(),
                                    'current_page' => (int) $this->page,
                                    'page_count'   => $this->total > 1 ? ceil($this->total / $this->per_page) : 1,
                                    'link_count'   => 5,
                                    'next'         => true,
                                ]
                            );
                        ?>
                    </div>
                </div>

            <?php else: ?>

                <div class="fat big">No roles to show</div>

            <?php endif; ?>
        </div>
    </div>
</div>

<?php $this->inc('admin/templates/footer'); ?>