<?php $this->inc('admin/templates/header'); ?>

<script>
    (function(){
        var self = {},
            div;

        $(function() {
            div = $("div#page");

            // Nav form
            $(".nav form", div)
                .on("submit", function(e) {
                    e.preventDefault();
                });

            // List forms
            $(".inside form", div)
                .on("submit", function(e) {
                    e.preventDefault();
                });

            $("button[name='new']", div)
                .on("click", function(){
                    location.href = "/admin/acl/role/new";
                });

            // Update
            $("form[name='update']", div)
                .on("submit", function(e){

                    e.preventDefault();

                    var form = $(this);

                    Core.ajax({
                        url: form.attr("action"),
                        data: {
                            "name": $("input[name='name']", form).val()
                        },
                        success: function(response) {
                            if (response.status === 'good') {
                                CoreDialog.alert("Role info has been saved", null, "good");
                            } else {
                                CoreDialog.alert(response.message || "Role info has not be updated");
                            }

                            $(".error", form).hide();

                            if (response && response.errors) {
                                for (var k in response.errors) {
                                    $(".id-error-" + k, form).html(response.errors[k]).show();
                                }
                            }
                        },
                        error: function(response) {
                            alert("There was a problem saving your role info");
                        }
                    });
                });

            // Resources
            $("form[name='resources']", div)
                .on("submit", function(e){

                    e.preventDefault();

                    var form = $(this);

                    var resource_ids = [];
                    $("input[name='resource[]']:checked", form).each(function(){
                        resource_ids.push($(this).val());
                    });

                    Core.ajax({
                        url: form.attr("action"),
                        data: {
                            "resources": resource_ids.join(",")
                        },
                        success: function(response) {
                            if (response.status === 'good') {
                                CoreDialog.alert("Role resources have been saved", null, "good");
                            } else {
                                CoreDialog.alert(response.message || "Role resources could not be updated");
                            }

                            $(".error", form).hide();

                            if (response && response.errors) {
                                for (var k in response.errors) {
                                    $(".id-error-" + k, form).html(response.errors[k]).show();
                                }
                            }
                        },
                        error: function(response) {
                            alert("There was a problem saving your role resources");
                        }
                    });
                });
        });

        return self;
    })();

</script>

<div id="page">

    <h3 class="header">
        <a href="/admin"><?php echo htmlspecialchars($this->locale->translate('Admin')); ?></a>
        / <a href="/admin/acl"><?php echo htmlspecialchars($this->locale->translate('ACL')); ?></a>
        / <a href="/admin/acl/role"><?php echo htmlspecialchars($this->locale->translate('Roles')); ?></a>
        / <?php echo htmlspecialchars($this->role->name); ?>
    </h3>

    <?php $this->inc('admin/templates/sidebar'); ?>

    <div>
        <div class="nav">
            <div class="side">
                <form>
                    <button name="new" class="btn"><?php echo htmlspecialchars($this->locale->translate('New')); ?></button>
                </form>
            </div>
        </div>

        <div class="inside">
            <div class="box">
                <div class="table-head">
                    <?php echo htmlspecialchars($this->locale->translate('Role')); ?>
                </div>
                <form name="update" action="/admin/acl/role/ajax/update/id:<?php echo $this->role->id; ?>">
                    <div class="table-body">
                        <div style="padding: 10px 0;">
                            <table width="100%">
                                <tr>
                                    <td width="175" align="right">
                                        <label name="name">Name</label>
                                        <div name="name" class="tiny error" style="display: none;"></div>
                                    </td>
                                    <td width="10"></td>
                                    <td>
                                        <input type="text" name="name" value="<?php echo htmlspecialchars($this->role->name); ?>" style="width: 300px;" />
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                    <div class="table-foot">
                        <button class="good" style="margin: 0 0 0 177px;">Update</button>
                    </div>
                </form>
            </div>
        </div>

        <div class="inside">
            <div class="box">
                <div class="table-head">
                    Roles
                </div>
                <form name="resources" action="/admin/acl/role/ajax/update_resources/id:<?php echo $this->role->id; ?>">
                    <div class="table-body">
                        <ul>
                            <?php foreach ($this->resources as $resource): ?>
                                <li>
                                    <label>
                                        <input type="checkbox" name="resource[]" value="<?php echo $resource->id; ?>" <?php if (in_array($resource->id, $this->role->acl_resource_collection()->field('id'))) { echo 'checked="checked" '; } ?>/>
                                        <b><?php echo htmlspecialchars($resource->slug()); ?></b>
                                    </label>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                    <div class="table-foot">
                        <button class="good">Update</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>

<?php $this->inc('admin/templates/footer'); ?>