<script>
    var messageEl = $("div#message", elements.body);
    var originalMessage = messageEl.text();

    $("form", elements.dialog).on("submit", function(e) {
        e.preventDefault();

        var emailEl = $("input[name='email']", elements.dialog);

        Core.ajax({
            "url": "/account/ajax/password_lost",
            "data": {
                "email": emailEl.val()
            },
            "success": function(response) {
                if (response.status === 'good') {
                    CoreDialog.done();
                    alert("Please check your email. You have been sent a link to reset your password.");
                } else {
                    if (response.message) {
                        var message = response.message;
                    } else {
                        var message = "There was a problem requesting a new password, please make sure your email address is correct.";
                    }

                    var labelEl = $("label[name='email']", elements.dialog);

                    messageEl
                       .text(message)
                       .addClass("error")
                       .removeClass("info");

                    emailEl.addClass("error");
                    labelEl.addClass("error");

                    CoreDialog.bodyResized();

                    emailEl.on("keydown", function(e) {
                        messageEl
                           .text(originalMessage)
                           .addClass("info")
                           .removeClass("error");

                        emailEl.removeClass("error");
                        labelEl.removeClass("error");

                        CoreDialog.bodyResized();
                    });
                }
            }
        });
    });

    $("a[name='login']", elements.dialog).on("click", function(e) {
       e.preventDefault();
       CoreDialog.done();
       CoreDialog.showUrl("/account/ajax/dialog/login");
    });
</script>