<form name="login" style="margin: 0 auto; display: block;">	
    <div class="regular-body" style="padding: 0 0 10px 0;">
    	<div class="padded info" id="message">
        	Please enter your email address to reset your password       	
    	</div>
    	<table width="100%">
    		<tr>
    			<td width="90" align="right">			
    				<strong>Email</strong>
    			</td>
    			<td width="10">&nbsp;</td>
    			<td>
    				<input type="text" name="email" style="width: 403px; font-size: 14px; line-height: 18px; padding: 5px 8px;" tabindex="1" />
    			</td>
    		</tr>
    	</table>
    </div>
    <input type="submit" style="position: fixed; left: -9999px"/>
</form>
