<?php $this->inc('admin/templates/header'); ?>

    <script>
        var page = {

            onload: function() {
                page.div = $("#page");
                page.i   = 0;

                // Nav form
                $(".nav form", page.div).on("submit", function(e) {
                    e.preventDefault();
                });

                // List forms
                $(".inside form", page.div).on("submit", function(e) {
                    e.preventDefault();
                });

                $("button[name='new']", page.div)
                    .on("click", function(){
                        CoreDialog.prompt(
                            null,
                            "Please enter the translation key",
                            [
                                {
                                    "type": "text",
                                    "label": "Translation Key",
                                    "name": "key",
                                    "css": {
                                        "width": "300px"
                                    }
                                },
                                {
                                    "type": "select",
                                    "label": "Namespace",
                                    "name": "namespace",
                                    "options": <?php echo json_encode($this->namespaces); ?>,
                                    "css": {
                                        "padding": "10px"
                                    }
                                }
                            ],
                            [
                                {
                                    "label": "Save",
                                    "action": function() {
                                        page.create(
                                            $("input[name='key']", this.elements.form).val(),
                                            $("select[name='namespace']", this.elements.form).val()
                                        );
                                    },
                                    "cssClass": "good"
                                }
                            ]
                        );
                    });

                $("ul.list li", page.div).on("click", page.activateEdit);

                page.translations = <?php echo json_encode($this->translations); ?>;
                page.locales      = <?php echo json_encode($this->locales); ?>;

                for (var id in page.translations) {
                    page.addRow(id);
                }
            },

            translationText: function(id, locale) {
                return ;
            },

            addRow: function(id) {
                var info = page.translations[id];

                var messages = $("<div/>");
                for (var locale in info["messages"]) {
                    messages
                        .append(
                            $("<div/>")
                                .append(
                                    $("<span/>")
                                        .css({
                                            "font-size": "11px",
                                            "font-weight": "bold"
                                        })
                                        .html(page.locales[locale])
                                )
                                .append(
                                    $("<div/>")
                                        .addClass("translation")
                                        .html(page.translations[id]["messages"][locale] ? page.translations[id]["messages"][locale] : "&laquo;NOT SET&raquo;")
                                        .on("click", function(e) {
                                            var self = $(this);

                                            if (! $("form", self).length) {
                                                self
                                                    .html("")
                                                    .append(
                                                        $("<form/>")
                                                            .append(
                                                                $("<input/>")
                                                                    .attr("type", "text")
                                                                    .css("width", "340px")
                                                                    .val(page.translations[id]["messages"][locale])
                                                            )
                                                            .on("submit", function(e){
                                                                var val = $("input", this).val();
                                                                page.update(id, locale, val);
                                                                page.translations[id]["messages"][locale] = val;
                                                                $("form", self).remove();
                                                                self.html(page.translations[id]["messages"][locale] ? page.translations[id]["messages"][locale] : "&laquo;NOT SET&raquo;")
                                                                e.preventDefault();
                                                            })
                                                    );

                                                $("input", self).focus();
                                            }

                                            e.preventDefault();
                                        })
                                )
                        );
                }

                $("<li/>")
                    .attr("id", "message-" + id)
                    .data("id", id)
                    .addClass(page.i++ % 2 === 1 ? "on" : "off")
                    .append(
                        $("<table/>")
                            .css("width", "100%")
                            .append(
                                $("<tr/>")
                                    .append(
                                        $("<td/>")
                                            .addClass("translation-key")
                                            .html(info["key"])
                                    )
                                    .append(
                                        $("<td/>")
                                            .css({
                                                "width": "30",
                                                "text-align": "center"
                                            })
                                            .append(
                                                $("<div/>").addClass("icon arrow-right")
                                            )
                                    )
                                    .append(
                                        $("<td/>")
                                            .addClass("translation-message")
                                            .css("width", "50%")
                                            .append(messages)
                                    )
                                    .append(
                                        $("<td/>")
                                            .css({
                                                "width": "100",
                                                "text-align": "right"
                                            })
                                            .append(
                                                $("<button/>")
                                                    .html("<?php echo htmlspecialchars($this->locale->translate('Delete')); ?>")
                                                    .addClass("error")
                                                    .on("click", function() {
                                                        page.del(
                                                            $(this)
                                                                .parents("li")
                                                                .data("id")
                                                        );
                                                    })
                                            )
                                    )
                            )
                    )
                    .appendTo("#translations");
            },

            create: function(body, namespace_id) {

                Core.ajax({
                    url: "/admin/locale/messages/ajax/create",
                    data: {
                        "locale":         "en",
                        "body":         body,
                        "namespace_id": namespace_id
                    },
                    success: function(response) {
                        if (response.status === 'good') {
                            CoreDialog.close();
                            location.href = location.href;
                        } else {
                            if (response.message && response.message.length) {
                                alert(response.message);
                            }
                        }
                    },
                    error: function(response) {
                        alert("There was a problem saving your translation key, please try again.");
                    }
                });
            },

            update: function(id, locale, body) {

                Core.ajax({
                    url: "/admin/locale/messages/ajax/update",
                    data: {
                        "key_id": id,
                        "locale": locale,
                        "body":   body
                    },
                    success: function(response) {
                        if (response.status === 'good') {
                            return;
                        } else {
                            if (response.message && response.message.length) {
                                alert(response.message);
                            }
                        }
                    },
                    error: function(response) {
                        alert("There was a problem saving your translation, please try again.");
                    }
                });
            },

            del: function(id) {
                Core.ajax({
                    url: "/admin/locale/messages/ajax/delete/id:" + id,
                    success: function(response) {
                        if (response.status === 'good') {
                            alert("Translation deleted");

                            $("ul#translations li#message-" + id)
                                .slideUp(500, function(){
                                    $(this).remove();
                                })

                        } else {
                            if (response.message && response.message.length) {
                                alert(response.message);
                            }
                        }
                    },
                    error: function(response) {
                        alert("There was a problem saving your translation, please try again.");
                    }
                });
            },

            activateEdit: function(e) {
                var tdKey         = $("td.key", this);
                var tdMessage     = $("td.message", this);
            }
        };

        $(page.onload);

    </script>

    <style>
        .translation-key {
            font-size: 14px;
            line-height: 18px;
            font-family: courier;
        }

        .translation-message {
            cursor: pointer;
            font-size: 14px;
            line-height: 18px;
            font-family: courier;
        }
        .translation-message:hover {
            text-decoration: underline;
        }

    </style>

    <div id="page">

        <h3 class="header">
            <a href="<?php $this->locale->route('/admin'); ?>"><?php echo htmlspecialchars($this->locale->translate('Admin')); ?></a>
            / <a href="<?php $this->locale->route('/admin/locale'); ?>"><?php echo htmlspecialchars($this->locale->translate('Locale')); ?></a>
            / <?php echo htmlspecialchars($this->locale->translate('Translations')); ?></h3>

        <?php $this->inc('admin/templates/sidebar'); ?>
        <div>
            <div class="nav">
                <div class="side">
                    <form>
                        <button name="new" class="btn"><?php echo htmlspecialchars($this->locale->translate('New Translation')); ?></button>
                    </form>
                </div>
            </div>

            <div class="inside">

                <?php if ($this->translations && count($this->translations)): ?>

                    <div class="box">
                        <div class="table-head">
                            <table width="100%" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td>
                                        <?php echo htmlspecialchars($this->locale->translate('Key')); ?>
                                    </td>
                                    <td width="30">
                                        &nbsp;
                                    </td>
                                    <td width="50%">
                                        <?php echo htmlspecialchars($this->locale->translate('Translation')); ?>
                                    </td>
                                    <td width="100">
                                        &nbsp;
                                    </td>
                                </tr>
                            </table>
                        </div>

                        <form>
                            <div class="table-body">
                                <ul id="translations"></ul>
                            </div>
                        </form>
                    </div>

                <?php else: ?>

                    <div class="fat big"><?php echo htmlspecialchars($this->locale->translate('No translations to show')); ?></div>

                <?php endif; ?>
            </div>
        </div>
    </div>

<?php $this->inc('admin/templates/footer'); ?>