<?php $this->inc('admin/templates/header'); ?>

<script>
    var page = {

        onload: function() {
            page.div     = $("#page");
            page.i         = 0;

            // Nav form
            $(".nav form", page.div).on("submit", function(e) {
                e.preventDefault();
            });

            // List forms
            $(".inside form", page.div).on("submit", function(e) {
                e.preventDefault();
            });

            $("button[name='new']", page.div)
                .on("click", function(){
                    CoreDialog.prompt(
                        "",
                        "New Namespace",
                        [
                            {
                                "type": "text",
                                "label": "Name",
                                "name": "name",
                                "css": {
                                    "width": "300px"
                                }
                            }
                        ],
                        [
                            {
                                "label": "Save",
                                "action": function() {
                                    console.log($("input[name='name']", this.elements.form).val());
                                    Core.ajax({
                                        "url": "/admin/locale/namespaces/ajax/insert",
                                        "data": {
                                            "name": $("input[name='name']", this.elements.form).val()
                                        },
                                        "success": function(response) {
                                            if (response.status === "good") {
                                                location.href = location.href;
                                            } else {
                                                CoreDialog.alert("A namespace with that name already exists");
                                            }
                                        }
                                    });

                                },
                                "cssClass": "good"
                            }
                        ]
                    );
                });
        }
    };

    $(page.onload);

</script>

<div id="page">

    <h3 class="header">
        <a href="<?php echo $this->locale->route('/admin'); ?>"><?php echo htmlspecialchars($this->locale->translate('Admin')); ?></a>
        / <a href="<?php echo $this->locale->route('/admin/locale'); ?>"><?php echo htmlspecialchars($this->locale->translate('Locale')); ?></a>
        / <?php echo htmlspecialchars($this->locale->translate('Namespaces')); ?>
    </h3>

    <?php $this->inc('admin/templates/sidebar'); ?>
    <div>
        <div class="nav">
            <div class="side">
                <form>
                    <button name="new" class="btn"><?php echo htmlspecialchars($this->locale->translate('New Namespace')); ?></button>
                </form>
            </div>
        </div>

        <div class="inside">

            <?php if ($this->namespaces): ?>

                <div class="box">
                    <div class="table-head">
                        <table width="100%" cellspacing="0" cellpadding="0">
                            <tr>
                                <td width="100">
                                    ID
                                </td>
                                <td>
                                    Name
                                </td>
                            </tr>
                        </table>
                    </div>

                    <div class="table-body">
                        <ul id="roles">
                            <?php foreach ($this->namespaces as $namespace): ?>
                                <li>
                                    <table width="100%" cellspacing="0" cellpadding="0">
                                        <tr>
                                            <td width="100">
                                                <?php echo $namespace->id; ?>
                                            </td>
                                            <td>
                                                <a href="<?php echo $this->locale->route('/admin/locale/namespaces/messages'); ?>/id:<?php echo $namespace->id; ?>"><b><?php echo htmlspecialchars($namespace->name); ?></b></a>
                                            </td>
                                        </tr>
                                    </table>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                </div>

            <?php else: ?>

                <div class="fat big">No namespaces to show</div>

            <?php endif; ?>
        </div>
    </div>
</div>

<?php $this->inc('admin/templates/footer'); ?>